#!/usr/bin/env bash

#/ command: sql:add-verb-to-home-pers: "adds"
#/ usage: rerun sql:add-verb-to-home-pers [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "add-verb-to-home-pers" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

