#!/usr/bin/env bash

#/ command: config:init: "it initializes config in pwd folder and it sets default core.home to pwd"
#/ usage: rerun config:init [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "init" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
export EM_CORE_HOME=$(pwd)


install_shell_tools ()
{
	if [ ! -d "$EM_CORE_HOME/shell_tools" ]; then
		echo cloning shell_tools
		git clone https://github.com/vecin2/shell_tools
	else
		echo "shell_tools already exist skipping clone git repo"
	fi
	
}	# ----------  end of function install_shell_tools  ----------


config_path=$(create_config_file "$@")

#prepend core_home = current directory
EM_CORE_HOME=$(pwd)
sed -i "1iexport EM_CORE_HOME=$EM_CORE_HOME" "$config_path"

install_shell_tools




echo "$config_path" updated

# Done. Exit with last command exit status.
exit $?

